server:
  port: 8002
spring:
  application:
    name: gateway-service
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seata?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&allowMultiQueries=true
      username: root
      password: 786679057
  redis:
    database: 0
    host: 192.168.10.136
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 0
        max-idle: 10
        max-wait: 1ms
        max-active: 200
    timeout: 1000ms
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8401/user/**
          predicates:
            - Path=/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

token:
  expire-time: 300

zuul:
  ignoredPatterns: /**/sso/**
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false